/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as FinancesIndexRouteImport } from './routes/finances.index'
import { Route as TodosTodoIdRouteImport } from './routes/todos.$todoId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as FinancesInvoiceIdRouteImport } from './routes/finances.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesIndexRoute = FinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdRoute = TodosTodoIdRouteImport.update({
  id: '/todos/$todoId',
  path: '/todos/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesInvoiceIdRoute = FinancesInvoiceIdRouteImport.update({
  id: '/finances/$invoiceId',
  path: '/finances/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finances/$invoiceId': typeof FinancesInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/finances/': typeof FinancesIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/todos/': typeof TodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finances/$invoiceId': typeof FinancesInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/finances': typeof FinancesIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/todos': typeof TodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finances/$invoiceId': typeof FinancesInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/finances/': typeof FinancesIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/todos/': typeof TodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finances/$invoiceId'
    | '/patients/$patientId'
    | '/sessions/$sessionId'
    | '/todos/$todoId'
    | '/finances/'
    | '/patients/'
    | '/sessions/'
    | '/settings/'
    | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finances/$invoiceId'
    | '/patients/$patientId'
    | '/sessions/$sessionId'
    | '/todos/$todoId'
    | '/finances'
    | '/patients'
    | '/sessions'
    | '/settings'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/finances/$invoiceId'
    | '/patients/$patientId'
    | '/sessions/$sessionId'
    | '/todos/$todoId'
    | '/finances/'
    | '/patients/'
    | '/sessions/'
    | '/settings/'
    | '/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancesInvoiceIdRoute: typeof FinancesInvoiceIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TodosTodoIdRoute: typeof TodosTodoIdRoute
  FinancesIndexRoute: typeof FinancesIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances/': {
      id: '/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof FinancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances/$invoiceId': {
      id: '/finances/$invoiceId'
      path: '/finances/$invoiceId'
      fullPath: '/finances/$invoiceId'
      preLoaderRoute: typeof FinancesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancesInvoiceIdRoute: FinancesInvoiceIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TodosTodoIdRoute: TodosTodoIdRoute,
  FinancesIndexRoute: FinancesIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
